name: Increment Version

on:
  push:
    branches:
      - main # Set to your default branch

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # It's important to perform a full depth checkout so that all tags are available for versioning

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Set this to the node version you want to use

      - name: Install dependencies
        run: npm install

      - name: Bump version
        id: bump_version
        run: |
          # This assumes you want to bump the patch version
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          IFS='.' read -ra VERSION_PARTS <<< "$PACKAGE_VERSION"
          PATCH_VERSION=$((VERSION_PARTS[2]+1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
          echo "New version: $NEW_VERSION"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"
          npm version $NEW_VERSION --no-git-tag-version

      - name: Commit and push
        run: |
          git config --local user.email "alpsenel@outlook.com"
          git config --local user.name "alpsenel"
          git add package.json
          git commit -m "ci: Bump version to ${{ steps.bump_version.outputs.NEW_VERSION }}"
          git push
