name: Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  job_one:
    name: "Version Update"
    runs-on: self-runner-node16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Bump version
        id: bump_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          IFS='.' read -ra VERSION_PARTS <<< "$PACKAGE_VERSION"
          PATCH_VERSION=$((VERSION_PARTS[2] + 1))
          if [[ "${VERSION_PARTS[2]}" -eq 99 ]]; then
              MINOR_VERSION=$((VERSION_PARTS[1] + 1))
              PATCH_VERSION=0
          else
              PATCH_VERSION=$((VERSION_PARTS[2] + 1))
              MINOR_VERSION=${VERSION_PARTS[1]}
          fi
          NEW_VERSION="${VERSION_PARTS[0]}.$MINOR_VERSION.$PATCH_VERSION"
          echo "New version: $NEW_VERSION"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"
          npm version $NEW_VERSION --no-git-tag-version

      - name: Commit and push
        run: |
          git config --global user.email "alpsenel@outlook.com"
          git config --global user.name "Emrah Polatcan"
          git add package.json
          git commit -m "ci: Bump version to ${{ steps.bump_version.outputs.NEW_VERSION }}"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}

  job_two:
    needs: [job_one]
    name: "Merge Develop to Master"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: git checkout master
      - run: |
         git config --global user.email "alpsenel@outlook.com"
         git config --global user.name "alpsenell"
      - run: git merge origin/develop
      - run: git push https://${{secrets.GH_ACTION_TOKEN}}@github.com/useinsider/insider-design-system.git master
